### PR TITLE
Carousel a11y tweaks

### PR DESCRIPTION
**Pull request by keirog**
Adds descriptive carousel buttons when navigating the page via a list of form controls. Uses composite aria labels 🎉  There’s still more we could do, but that can wait (if carousels survive long enough).

@lc512k 

Before | After
---|---
before | after

### CODE REVIEW

**Comment by keirog** [comment]
Resolves https://github.com/Financial-Times/next-a11y/issues/62

**Comment by lc512k** [comment]
❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ 

lets just hope that kind of stuff happens now magically while we're not looking 🙈

**Comment by ironsidevsquincy** [comment]
Cool. Thanks

**Comment by keirog** [comment]
@lc512k 
not-enough-reactions
Not enough reactions 😿

**Comment by lc512k** [comment]
😭 😂 
http://data.whicdn.com/images/63365887/large.gif

**Pull request merged**
